#!/bin/sh

set -e

lb config noauto \
     --binary-images netboot \
     --mirror-bootstrap http://ftp.pl.debian.org/debian/ \
     --mirror-binary http://ftp.pl.debian.org/debian/ \
     --apt-indices false \
	"${@}"
